# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-29 13:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.CharField(max_length=32, verbose_name='seed')),
                ('method', models.CharField(choices=[(b'generator', 'Token generator (iPhone/Android App)'), (b'sms', 'Text message')], max_length=16, verbose_name='authentication method')),
                ('phone', models.CharField(max_length=16, verbose_name='phone number')),
                ('backup_phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='backup phone number')),
                ('last_sent', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tf_token', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedComputer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_until', models.DateTimeField(verbose_name='verified until')),
                ('ip', models.GenericIPAddressField(verbose_name='IP address')),
                ('last_used_at', models.DateTimeField(verbose_name='last used at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tf_verified_computers', to=settings.AUTH_USER_MODEL, verbose_name='verified computer')),
            ],
        ),
    ]
